import Link from "next/link";
import Footer from "@/components/Footer";

export const metadata = { title: "Terms of Service — Ascent" };

const sections = [
  {
    num: "01",
    title: "Acceptance of Terms",
    body: [
      "By accessing or using Ascent (\u201cthe App\u201d), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the App. These terms apply to all users, including those in early access.",
    ],
  },
  {
    num: "02",
    title: "Description of Service",
    body: [
      "Ascent is a personal operating system designed to help individuals track their work output, behavioral compliance, and personal development. The App includes task management, time tracking, calendar integration, compliance logging, analytics, and an AI advisory layer.",
      "Features are provided as-is and may change, be added, or be removed at any time during early access and development.",
    ],
  },
  {
    num: "03",
    title: "Your Data",
    body: [
      "All data you enter into Ascent — tasks, compliance logs, session times, notes — is yours. We do not sell your data. We do not use your personal behavioral data to train AI models without your explicit consent.",
      "You are responsible for maintaining the accuracy of data you enter. Ascent does not verify the completeness or correctness of your personal records.",
    ],
  },
  {
    num: "04",
    title: "AI Advisory Layer",
    body: [
      "The AI Advisor feature provides guidance based on data you voluntarily input. It does not constitute professional advice — financial, psychological, medical, or otherwise. Responses are generated by a language model and may be inaccurate or incomplete.",
      "You agree not to rely on the AI Advisor as a substitute for professional consultation in any domain.",
    ],
  },
  {
    num: "05",
    title: "Prohibited Use",
    body: [
      "You agree not to use Ascent to store or process unlawful content, attempt to reverse-engineer or exploit the App, circumvent security measures, or impersonate other users. Violation of these terms may result in immediate termination of access.",
    ],
  },
  {
    num: "06",
    title: "Disclaimers",
    body: [
      "Ascent is provided without warranty of any kind. We make no guarantees regarding uptime, accuracy, or fitness for a particular purpose. Use of the App is at your own risk.",
    ],
  },
  {
    num: "07",
    title: "Changes to Terms",
    body: [
      "We may update these Terms at any time. Continued use of Ascent after changes are posted constitutes acceptance of the revised terms. We will make reasonable efforts to notify users of material changes.",
    ],
  },
  {
    num: "08",
    title: "Contact",
    body: [
      "Questions about these terms can be directed to the Ascent development team. During early access, reach out via the waitlist contact channel.",
    ],
  },
];

export default function TermsPage() {
  return (
    <>
      <nav
        className="fixed top-0 left-0 right-0 z-100 px-6 md:px-15 py-[18px] flex items-center justify-between border-b"
        style={{
          borderColor: "var(--border)",
          background: "rgba(10,10,12,0.92)",
          backdropFilter: "blur(12px)",
        }}
      >
        <Link
          href="/"
          className="flex items-center gap-2.5 font-display text-[15px] font-bold tracking-[0.01em] text-text-primary no-underline"
        >
          <img src="/logo.svg" alt="Ascent" className="w-5 h-5" />
          Ascent
        </Link>
        <Link
          href="/"
          className="text-[11px] text-text-secondary tracking-[0.05em] no-underline hover:text-text-mid transition-colors duration-150"
        >
          ← Back to Ascent
        </Link>
      </nav>

      <div className="max-w-[720px] mx-auto px-6 md:px-15 pt-[100px] md:pt-[120px] pb-16 md:pb-[100px]">
        <div className="text-[10px] tracking-[0.15em] uppercase text-text-secondary mb-4">
          Legal
        </div>
        <h1
          className="font-display font-bold tracking-[-0.03em] leading-[1.05] mb-3"
          style={{ fontSize: "clamp(36px,5vw,56px)" }}
        >
          Terms of Service
        </h1>
        <div
          className="text-[11px] text-text-secondary tracking-[0.04em] mb-14 pb-8 border-b"
          style={{ borderColor: "var(--border)" }}
        >
          Last updated: March 19, 2026
        </div>

        {sections.map((s, i) => (
          <div key={s.num}>
            <div className="mb-12">
              <div className="font-display text-[14px] font-semibold tracking-[0.01em] mb-3 text-text-primary">
                <span className="text-[10px] tracking-[0.1em] text-text-secondary mr-2">
                  {s.num}
                </span>
                {s.title}
              </div>
              {s.body.map((p, j) => (
                <p
                  key={j}
                  className="text-[13px] text-text-secondary leading-[1.9] tracking-[0.02em] mb-3 last:mb-0"
                >
                  {p}
                </p>
              ))}
            </div>
            {i < sections.length - 1 && (
              <div
                className="h-px mb-12"
                style={{ background: "var(--border)" }}
              />
            )}
          </div>
        ))}
      </div>

      <Footer />
    </>
  );
}
